---
- hosts: all
  vars:
    games: [cricket, football, baseball, trackevents]
  tasks:
  - name: print list varaiable
    debug:
      msg: "{{ item }}"
    with_items:
      - "{{ games }}"












